// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "execute.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic execute::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic execute::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> execute::ap_ST_fsm_state1 = "1";
const sc_lv<3> execute::ap_ST_fsm_state2 = "10";
const sc_lv<3> execute::ap_ST_fsm_state3 = "100";
const sc_lv<32> execute::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> execute::ap_const_lv32_1 = "1";
const sc_lv<1> execute::ap_const_lv1_0 = "0";
const sc_lv<32> execute::ap_const_lv32_2 = "10";
const sc_lv<1> execute::ap_const_lv1_1 = "1";
const sc_lv<64> execute::ap_const_lv64_86 = "10000110";
const sc_lv<32> execute::ap_const_lv32_4 = "100";
const bool execute::ap_const_boolean_1 = true;

execute::execute(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_agg_result_delete_el_phi_fu_58_p4);
    sensitive << ( key_to_metadata_occu_3_reg_82 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_9_fu_66_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_phi_mux_agg_result_delete_el_phi_fu_58_p4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_key_to_metadata_key_address0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_key_to_metadata_key_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_key_to_metadata_occu_2_reg_72);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_key_to_metadata_occu_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( key_to_metadata_occu_2_reg_72 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_key_to_metadata_occu_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_key_to_metadata_occu_d0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_key_to_metadata_occu_we0);
    sensitive << ( key_to_metadata_occu_3_reg_82 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_9_fu_66_p2 );

    SC_METHOD(thread_tmp_9_fu_66_p2);
    sensitive << ( key_to_metadata_key_q0 );
    sensitive << ( key_to_metadata_occu_3_reg_82 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    ap_CS_fsm = "001";
    ap_return_preg = "0";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "execute_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, key_to_metadata_key_address0, "(port)key_to_metadata_key_address0");
    sc_trace(mVcdFile, key_to_metadata_key_ce0, "(port)key_to_metadata_key_ce0");
    sc_trace(mVcdFile, key_to_metadata_key_q0, "(port)key_to_metadata_key_q0");
    sc_trace(mVcdFile, key_to_metadata_occu_address0, "(port)key_to_metadata_occu_address0");
    sc_trace(mVcdFile, key_to_metadata_occu_ce0, "(port)key_to_metadata_occu_ce0");
    sc_trace(mVcdFile, key_to_metadata_occu_we0, "(port)key_to_metadata_occu_we0");
    sc_trace(mVcdFile, key_to_metadata_occu_d0, "(port)key_to_metadata_occu_d0");
    sc_trace(mVcdFile, key_to_metadata_occu_q0, "(port)key_to_metadata_occu_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, key_to_metadata_occu_2_reg_72, "key_to_metadata_occu_2_reg_72");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, key_to_metadata_occu_3_reg_82, "key_to_metadata_occu_3_reg_82");
    sc_trace(mVcdFile, ap_phi_mux_agg_result_delete_el_phi_fu_58_p4, "ap_phi_mux_agg_result_delete_el_phi_fu_58_p4");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_9_fu_66_p2, "tmp_9_fu_66_p2");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

execute::~execute() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void execute::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv1_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_return_preg = ap_phi_mux_agg_result_delete_el_phi_fu_58_p4.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        key_to_metadata_occu_3_reg_82 = key_to_metadata_occu_q0.read();
    }
}

void execute::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void execute::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void execute::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void execute::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void execute::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void execute::thread_ap_phi_mux_agg_result_delete_el_phi_fu_58_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        if ((esl_seteq<1,1,1>(key_to_metadata_occu_3_reg_82.read(), ap_const_lv1_0) || 
             esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_66_p2.read()))) {
            ap_phi_mux_agg_result_delete_el_phi_fu_58_p4 = ap_const_lv1_1;
        } else if ((esl_seteq<1,1,1>(key_to_metadata_occu_3_reg_82.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_fu_66_p2.read()))) {
            ap_phi_mux_agg_result_delete_el_phi_fu_58_p4 = ap_const_lv1_0;
        } else {
            ap_phi_mux_agg_result_delete_el_phi_fu_58_p4 = "X";
        }
    } else {
        ap_phi_mux_agg_result_delete_el_phi_fu_58_p4 = "X";
    }
}

void execute::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void execute::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ap_return = ap_phi_mux_agg_result_delete_el_phi_fu_58_p4.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void execute::thread_key_to_metadata_key_address0() {
    key_to_metadata_key_address0 =  (sc_lv<9>) (ap_const_lv64_86);
}

void execute::thread_key_to_metadata_key_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        key_to_metadata_key_ce0 = ap_const_logic_1;
    } else {
        key_to_metadata_key_ce0 = ap_const_logic_0;
    }
}

void execute::thread_key_to_metadata_occu_2_reg_72() {
    key_to_metadata_occu_2_reg_72 =  (sc_lv<9>) (ap_const_lv64_86);
}

void execute::thread_key_to_metadata_occu_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        key_to_metadata_occu_address0 = key_to_metadata_occu_2_reg_72.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        key_to_metadata_occu_address0 =  (sc_lv<9>) (ap_const_lv64_86);
    } else {
        key_to_metadata_occu_address0 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void execute::thread_key_to_metadata_occu_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        key_to_metadata_occu_ce0 = ap_const_logic_1;
    } else {
        key_to_metadata_occu_ce0 = ap_const_logic_0;
    }
}

void execute::thread_key_to_metadata_occu_d0() {
    key_to_metadata_occu_d0 = ap_const_lv1_0;
}

void execute::thread_key_to_metadata_occu_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(key_to_metadata_occu_3_reg_82.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_fu_66_p2.read()))) {
        key_to_metadata_occu_we0 = ap_const_logic_1;
    } else {
        key_to_metadata_occu_we0 = ap_const_logic_0;
    }
}

void execute::thread_tmp_9_fu_66_p2() {
    tmp_9_fu_66_p2 = (!key_to_metadata_key_q0.read().is_01() || !ap_const_lv32_4.is_01())? sc_lv<1>(): sc_lv<1>(key_to_metadata_key_q0.read() == ap_const_lv32_4);
}

void execute::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

}

