// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _execute_HH_
#define _execute_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct execute : public sc_module {
    // Port declarations 15
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<9> > key_to_metadata_key_address0;
    sc_out< sc_logic > key_to_metadata_key_ce0;
    sc_in< sc_lv<32> > key_to_metadata_key_q0;
    sc_out< sc_lv<9> > key_to_metadata_occu_address0;
    sc_out< sc_logic > key_to_metadata_occu_ce0;
    sc_out< sc_logic > key_to_metadata_occu_we0;
    sc_out< sc_lv<1> > key_to_metadata_occu_d0;
    sc_in< sc_lv<1> > key_to_metadata_occu_q0;
    sc_out< sc_lv<1> > ap_return;


    // Module declarations
    execute(sc_module_name name);
    SC_HAS_PROCESS(execute);

    ~execute();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<9> > key_to_metadata_occu_2_reg_72;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > key_to_metadata_occu_3_reg_82;
    sc_signal< sc_lv<1> > ap_phi_mux_agg_result_delete_el_phi_fu_58_p4;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_9_fu_66_p2;
    sc_signal< sc_lv<1> > ap_return_preg;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<64> ap_const_lv64_86;
    static const sc_lv<32> ap_const_lv32_4;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_agg_result_delete_el_phi_fu_58_p4();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_key_to_metadata_key_address0();
    void thread_key_to_metadata_key_ce0();
    void thread_key_to_metadata_occu_2_reg_72();
    void thread_key_to_metadata_occu_address0();
    void thread_key_to_metadata_occu_ce0();
    void thread_key_to_metadata_occu_d0();
    void thread_key_to_metadata_occu_we0();
    void thread_tmp_9_fu_66_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
