// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xtraffic_generate_and_execute.h"

extern XTraffic_generate_and_execute_Config XTraffic_generate_and_execute_ConfigTable[];

XTraffic_generate_and_execute_Config *XTraffic_generate_and_execute_LookupConfig(u16 DeviceId) {
	XTraffic_generate_and_execute_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XTRAFFIC_GENERATE_AND_EXECUTE_NUM_INSTANCES; Index++) {
		if (XTraffic_generate_and_execute_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XTraffic_generate_and_execute_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XTraffic_generate_and_execute_Initialize(XTraffic_generate_and_execute *InstancePtr, u16 DeviceId) {
	XTraffic_generate_and_execute_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XTraffic_generate_and_execute_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XTraffic_generate_and_execute_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

