// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xtraffic_generate_and_execute.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XTraffic_generate_and_execute_CfgInitialize(XTraffic_generate_and_execute *InstancePtr, XTraffic_generate_and_execute_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XTraffic_generate_and_execute_Start(XTraffic_generate_and_execute *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTraffic_generate_and_execute_ReadReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_AP_CTRL) & 0x80;
    XTraffic_generate_and_execute_WriteReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XTraffic_generate_and_execute_IsDone(XTraffic_generate_and_execute *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTraffic_generate_and_execute_ReadReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XTraffic_generate_and_execute_IsIdle(XTraffic_generate_and_execute *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTraffic_generate_and_execute_ReadReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XTraffic_generate_and_execute_IsReady(XTraffic_generate_and_execute *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTraffic_generate_and_execute_ReadReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XTraffic_generate_and_execute_EnableAutoRestart(XTraffic_generate_and_execute *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTraffic_generate_and_execute_WriteReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XTraffic_generate_and_execute_DisableAutoRestart(XTraffic_generate_and_execute *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTraffic_generate_and_execute_WriteReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_AP_CTRL, 0);
}

void XTraffic_generate_and_execute_InterruptGlobalEnable(XTraffic_generate_and_execute *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTraffic_generate_and_execute_WriteReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_GIE, 1);
}

void XTraffic_generate_and_execute_InterruptGlobalDisable(XTraffic_generate_and_execute *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTraffic_generate_and_execute_WriteReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_GIE, 0);
}

void XTraffic_generate_and_execute_InterruptEnable(XTraffic_generate_and_execute *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTraffic_generate_and_execute_ReadReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_IER);
    XTraffic_generate_and_execute_WriteReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_IER, Register | Mask);
}

void XTraffic_generate_and_execute_InterruptDisable(XTraffic_generate_and_execute *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTraffic_generate_and_execute_ReadReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_IER);
    XTraffic_generate_and_execute_WriteReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_IER, Register & (~Mask));
}

void XTraffic_generate_and_execute_InterruptClear(XTraffic_generate_and_execute *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTraffic_generate_and_execute_WriteReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_ISR, Mask);
}

u32 XTraffic_generate_and_execute_InterruptGetEnabled(XTraffic_generate_and_execute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTraffic_generate_and_execute_ReadReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_IER);
}

u32 XTraffic_generate_and_execute_InterruptGetStatus(XTraffic_generate_and_execute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTraffic_generate_and_execute_ReadReg(InstancePtr->Axilites_BaseAddress, XTRAFFIC_GENERATE_AND_EXECUTE_AXILITES_ADDR_ISR);
}

