// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#1 "/home/bollu/work/CuckooHashingHLS/hls/cuckoo-hashing-hls/solution1/test/test_conv.cpp"
#1 "<built-in>"
#1 "<command-line>"
#1 "/home/bollu/work/CuckooHashingHLS/hls/cuckoo-hashing-hls/solution1/test/test_conv.cpp"
#1 "/home/bollu/work/CuckooHashingHLS/hls/cuckoo-hashing-hls/solution1/test/../src/conv.h" 1
void axpy(int in[3], int a, int b, int out[3]);
#2 "/home/bollu/work/CuckooHashingHLS/hls/cuckoo-hashing-hls/solution1/test/test_conv.cpp" 2




#ifndef HLS_FASTSIM
#5 "/home/bollu/work/CuckooHashingHLS/hls/cuckoo-hashing-hls/solution1/test/test_conv.cpp"

#ifndef HLS_FASTSIM
#include "apatb_axpy.h"
#endif

#5 "/home/bollu/work/CuckooHashingHLS/hls/cuckoo-hashing-hls/solution1/test/test_conv.cpp"
int main() {
 int in[1][3] = {{1, 2, 3}};
 int a[1] = {1};
 int b[1] = {2};
 int gold[1][3];
 int out[1][3];




 for(int i = 0; i < 1; i++) {
  
#ifndef HLS_FASTSIM
#define axpy AESL_WRAP_axpy
#endif

#16 "/home/bollu/work/CuckooHashingHLS/hls/cuckoo-hashing-hls/solution1/test/test_conv.cpp"

#ifndef HLS_FASTSIM
#define axpy AESL_WRAP_axpy
#endif

#16 "/home/bollu/work/CuckooHashingHLS/hls/cuckoo-hashing-hls/solution1/test/test_conv.cpp"
axpy
#undef axpy
#16 "/home/bollu/work/CuckooHashingHLS/hls/cuckoo-hashing-hls/solution1/test/test_conv.cpp"

#undef axpy
#16 "/home/bollu/work/CuckooHashingHLS/hls/cuckoo-hashing-hls/solution1/test/test_conv.cpp"
(in[i], a[i], b[i], out[i]);
 }


 for(int i = 0; i < 1; i++) {
  for(int j = 0; j < 3; j++) {
   gold[i][j] = a[i] * in[i][j] + b[i];
  }
 }

 for(int i = 0; i < 1; i++) {
  for(int j = 0; j < 3; j++) {
   if(gold[i][j] != out[i][j]) return 1;
  }
 }

 return 0;
}
#endif
#33 "/home/bollu/work/CuckooHashingHLS/hls/cuckoo-hashing-hls/solution1/test/test_conv.cpp"
