// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XTRAFFIC_GENERATE_AND_EXECUTE_H
#define XTRAFFIC_GENERATE_AND_EXECUTE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xtraffic_generate_and_execute_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XTraffic_generate_and_execute_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XTraffic_generate_and_execute;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XTraffic_generate_and_execute_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XTraffic_generate_and_execute_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XTraffic_generate_and_execute_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XTraffic_generate_and_execute_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XTraffic_generate_and_execute_Initialize(XTraffic_generate_and_execute *InstancePtr, u16 DeviceId);
XTraffic_generate_and_execute_Config* XTraffic_generate_and_execute_LookupConfig(u16 DeviceId);
int XTraffic_generate_and_execute_CfgInitialize(XTraffic_generate_and_execute *InstancePtr, XTraffic_generate_and_execute_Config *ConfigPtr);
#else
int XTraffic_generate_and_execute_Initialize(XTraffic_generate_and_execute *InstancePtr, const char* InstanceName);
int XTraffic_generate_and_execute_Release(XTraffic_generate_and_execute *InstancePtr);
#endif

void XTraffic_generate_and_execute_Start(XTraffic_generate_and_execute *InstancePtr);
u32 XTraffic_generate_and_execute_IsDone(XTraffic_generate_and_execute *InstancePtr);
u32 XTraffic_generate_and_execute_IsIdle(XTraffic_generate_and_execute *InstancePtr);
u32 XTraffic_generate_and_execute_IsReady(XTraffic_generate_and_execute *InstancePtr);
void XTraffic_generate_and_execute_EnableAutoRestart(XTraffic_generate_and_execute *InstancePtr);
void XTraffic_generate_and_execute_DisableAutoRestart(XTraffic_generate_and_execute *InstancePtr);


void XTraffic_generate_and_execute_InterruptGlobalEnable(XTraffic_generate_and_execute *InstancePtr);
void XTraffic_generate_and_execute_InterruptGlobalDisable(XTraffic_generate_and_execute *InstancePtr);
void XTraffic_generate_and_execute_InterruptEnable(XTraffic_generate_and_execute *InstancePtr, u32 Mask);
void XTraffic_generate_and_execute_InterruptDisable(XTraffic_generate_and_execute *InstancePtr, u32 Mask);
void XTraffic_generate_and_execute_InterruptClear(XTraffic_generate_and_execute *InstancePtr, u32 Mask);
u32 XTraffic_generate_and_execute_InterruptGetEnabled(XTraffic_generate_and_execute *InstancePtr);
u32 XTraffic_generate_and_execute_InterruptGetStatus(XTraffic_generate_and_execute *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
